// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNTvGaVusr2_yBA-8Ao_Nz_RuB2OV9jro',
    appId: '1:975486713969:web:5929122682ada9e2971bd0',
    messagingSenderId: '975486713969',
    projectId: 'proyecto-final-ok',
    authDomain: 'proyecto-final-ok.firebaseapp.com',
    storageBucket: 'proyecto-final-ok.firebasestorage.app',
    measurementId: 'G-38ETKK0ZTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0QW98jKI32FSJBDI1NGeKW093xd3A2ik',
    appId: '1:975486713969:android:7fbfb4696d755fcd971bd0',
    messagingSenderId: '975486713969',
    projectId: 'proyecto-final-ok',
    storageBucket: 'proyecto-final-ok.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC16y2Td1MsqCa5wpYdFT5FBy-3cPMODrk',
    appId: '1:975486713969:ios:d70d2f39c73fa762971bd0',
    messagingSenderId: '975486713969',
    projectId: 'proyecto-final-ok',
    storageBucket: 'proyecto-final-ok.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinalOk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC16y2Td1MsqCa5wpYdFT5FBy-3cPMODrk',
    appId: '1:975486713969:ios:d70d2f39c73fa762971bd0',
    messagingSenderId: '975486713969',
    projectId: 'proyecto-final-ok',
    storageBucket: 'proyecto-final-ok.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinalOk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNTvGaVusr2_yBA-8Ao_Nz_RuB2OV9jro',
    appId: '1:975486713969:web:dd522dba1ff60326971bd0',
    messagingSenderId: '975486713969',
    projectId: 'proyecto-final-ok',
    authDomain: 'proyecto-final-ok.firebaseapp.com',
    storageBucket: 'proyecto-final-ok.firebasestorage.app',
    measurementId: 'G-D0VMQEWB6Y',
  );
}
